### ISSUE TITLE
Heroku でビルドエラー

### ISSUE THREAD

**Issue by Kazuma** [Kazuma/sparkly#11]
気が向いたら対応する

```log
-----> Ruby app detected
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-1.9.2
-----> Installing dependencies using 1.6.3
       Purging Cache. Changing stack from cedar to cedar-14
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       fatal: Not a git repository (or any parent up to mount point /tmp)
       Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
       Fetching gem metadata from https://rubygems.org/..........
       Installing daemons 1.1.9
       Installing tilt 1.4.1
       Installing mini_portile 0.6.2
       Installing rack 1.6.0
       Using bundler 1.6.3
       Installing rinne 0.0.3
       Installing haml 4.0.6
       Installing rack-protection 1.5.3
       Installing sinatra 1.4.5
       Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.
       /app/vendor/ruby-1.9.2/bin/ruby extconf.rb
       *** extconf.rb failed ***
       Could not create Makefile due to some reason, probably lack of
       necessary libraries and/or headers.  Check the mkmf.log file for more
       details.  You may need configuration options.
       Provided configuration options:
       --with-opt-dir
       --without-opt-dir
       --with-opt-include
       --without-opt-include=${opt-dir}/include
       --with-opt-lib
       --without-opt-lib=${opt-dir}/lib
       --with-make-prog
       --without-make-prog
       --srcdir=.
       --curdir
       --ruby=/app/vendor/ruby-1.9.2/bin/ruby
       --help
       --clean
       /app/vendor/ruby-1.9.2/lib/ruby/1.9.1/mkmf.rb:445:in `try_compile': wrong number of arguments (3 for 2) (ArgumentError)
       from extconf.rb:77:in `block in add_cflags'
       from /app/vendor/ruby-1.9.2/lib/ruby/1.9.1/mkmf.rb:481:in `with_cflags'
       from extconf.rb:76:in `add_cflags'
       from extconf.rb:323:in `<main>'
       checking if the C compiler accepts ...
       Gem files will remain installed in /tmp/build_bcbf4b7e5c73879feed9b60b9e302f0c/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.6.5 for inspection.
       Results logged to /tmp/build_bcbf4b7e5c73879feed9b60b9e302f0c/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.6.5/ext/nokogiri/gem_make.out
       Installing eventmachine 1.0.4
       An error occurred while installing nokogiri (1.6.5), and Bundler cannot
       continue.
       Make sure that `gem install nokogiri -v '1.6.5'` succeeds before bundling.
       Bundler Output: fatal: Not a git repository (or any parent up to mount point /tmp)
       Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
       Fetching gem metadata from https://rubygems.org/..........
       Installing daemons 1.1.9
       Installing tilt 1.4.1
       Installing mini_portile 0.6.2
       Installing rack 1.6.0
       Using bundler 1.6.3
       Installing rinne 0.0.3
       Installing haml 4.0.6
       Installing rack-protection 1.5.3
       Installing sinatra 1.4.5
       
       Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.
       
       /app/vendor/ruby-1.9.2/bin/ruby extconf.rb
       *** extconf.rb failed ***
       Could not create Makefile due to some reason, probably lack of
       necessary libraries and/or headers.  Check the mkmf.log file for more
       details.  You may need configuration options.
       
       Provided configuration options:
       --with-opt-dir
       --without-opt-dir
       --with-opt-include
       --without-opt-include=${opt-dir}/include
       --with-opt-lib
       --without-opt-lib=${opt-dir}/lib
       --with-make-prog
       --without-make-prog
       --srcdir=.
       --curdir
       --ruby=/app/vendor/ruby-1.9.2/bin/ruby
       --help
       --clean
       /app/vendor/ruby-1.9.2/lib/ruby/1.9.1/mkmf.rb:445:in `try_compile': wrong number of arguments (3 for 2) (ArgumentError)
       from extconf.rb:77:in `block in add_cflags'
       from /app/vendor/ruby-1.9.2/lib/ruby/1.9.1/mkmf.rb:481:in `with_cflags'
       from extconf.rb:76:in `add_cflags'
       from extconf.rb:323:in `<main>'
       checking if the C compiler accepts ...
       
       Gem files will remain installed in /tmp/build_bcbf4b7e5c73879feed9b60b9e302f0c/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.6.5 for inspection.
       Results logged to /tmp/build_bcbf4b7e5c73879feed9b60b9e302f0c/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.6.5/ext/nokogiri/gem_make.out
       Installing eventmachine 1.0.4
       An error occurred while installing nokogiri (1.6.5), and Bundler cannot
       continue.
       Make sure that `gem install nokogiri -v '1.6.5'` succeeds before bundling.
 !
 !     Failed to install gems via Bundler.
 !

 !     Push rejected, failed to compile Ruby app
```

**Comment by Kazuma** [comment]
Heroku と GitHub を connect させて、 Automatic deploys を有効にしたらビルドエラー表示されなくなった
